name: Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

  build-windows:
    needs: version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Windows
        run: dotnet publish src/XboxBatteryMonitor/XboxBatteryMonitor.csproj -c Release -r win-x64 --self-contained -p:Version=${{ needs.version.outputs.semver }} -p:DebugType=None
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: XboxBatteryMonitor-Windows-${{ needs.version.outputs.semver }}
          path: src/XboxBatteryMonitor/bin/Release/net9.0/win-x64/publish/

  build-linux:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Linux
        run: dotnet publish src/XboxBatteryMonitor/XboxBatteryMonitor.csproj -c Release -r linux-x64 --self-contained -p:Version=${{ needs.version.outputs.semver }} -p:DebugType=None
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: XboxBatteryMonitor-Linux-${{ needs.version.outputs.semver }}
          path: src/XboxBatteryMonitor/bin/Release/net9.0/linux-x64/publish/

  release:
    needs: [version, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: XboxBatteryMonitor-Windows-${{ needs.version.outputs.semver }}
          path: artifacts/windows/
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: XboxBatteryMonitor-Linux-${{ needs.version.outputs.semver }}
          path: artifacts/linux/
      - name: Create archives
        run: |
          cd artifacts/windows
          zip -r ../../XboxBatteryMonitor-Windows-${{ needs.version.outputs.semver }}.zip .
          cd ../linux
          tar -czf ../../XboxBatteryMonitor-Linux-${{ needs.version.outputs.semver }}.tar.gz .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version.outputs.semver }}
          name: Release v${{ needs.version.outputs.semver }}
          body: |
            ## Xbox Battery Monitor v${{ needs.version.outputs.semver }}

            This release includes builds for Windows and Linux.

            ### Downloads
            - **Windows**: XboxBatteryMonitor-Windows-${{ needs.version.outputs.semver }}.zip
            - **Linux**: XboxBatteryMonitor-Linux-${{ needs.version.outputs.semver }}.tar.gz

            ### Features
            - Native AOT compilation for improved performance
            - Self-contained executables (no external dependencies required)
            - Single-file Linux executable

            ### Changes
            See commit history for detailed changes in this release.
          make_latest: true
          draft: false
          generate_release_notes: true
          files: |
            XboxBatteryMonitor-Windows-${{ needs.version.outputs.semver }}.zip
            XboxBatteryMonitor-Linux-${{ needs.version.outputs.semver }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}