name: Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

  build-windows:
    needs: version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Windows
        run: dotnet publish src/ControllerMonitor/ControllerMonitor.csproj -c Release -r win-x64 --self-contained -p:Version=${{ needs.version.outputs.semver }} -p:DebugType=None
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ControllerMonitor-Windows-${{ needs.version.outputs.semver }}
          path: src/ControllerMonitor/bin/Release/net9.0/win-x64/publish/

  build-linux:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Linux
        run: dotnet publish src/ControllerMonitor/ControllerMonitor.csproj -c Release -r linux-x64 --self-contained -p:Version=${{ needs.version.outputs.semver }} -p:DebugType=None
      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential libarchive-tools
          sudo gem install fpm
      - name: Create package structure
        run: |
          mkdir -p staging/usr/bin
          mkdir -p staging/usr/lib/controller-monitor
          mkdir -p staging/usr/share/icons/hicolor/256x256/apps
          mkdir -p staging/usr/share/applications

          # Copy executable to /usr/bin
          cp src/ControllerMonitor/bin/Release/net9.0/linux-x64/publish/ControllerMonitor staging/usr/bin/

          # Copy shared libraries to /usr/lib/appname
          cp src/ControllerMonitor/bin/Release/net9.0/linux-x64/publish/*.so staging/usr/lib/controller-monitor/

          # Create wrapper script that sets LD_LIBRARY_PATH
          cat > staging/usr/bin/controller-monitor << 'EOF'
          #!/bin/bash
          export LD_LIBRARY_PATH="/usr/lib/controller-monitor:$LD_LIBRARY_PATH"
          exec /usr/bin/ControllerMonitor "$@"
          EOF
          chmod +x staging/usr/bin/controller-monitor

          # Copy icon
          cp src/ControllerMonitor/Assets/icons/app.png staging/usr/share/icons/hicolor/256x256/apps/controller-monitor.png

          # Create desktop file using wrapper script
          cat > staging/usr/share/applications/controller-monitor.desktop << EOF
          [Desktop Entry]
          Name=Controller Monitor
          Comment=A cross-platform Avalonia UI application for monitoring game controller battery levels
          Exec=/usr/bin/controller-monitor
          Icon=controller-monitor
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF
      - name: Create deb package
        run: |
          fpm -s dir -t deb -n controller-monitor -v ${{ needs.version.outputs.semver }} \
            --description "A cross-platform Avalonia UI application for monitoring game controller battery levels" \
            --maintainer "SilentLeader <https://github.com/SilentLeader/>" \
            --url "https://github.com/SilentLeader/controller-battery-monitor" \
            --license "MIT" \
            -C staging .
          mv controller-monitor_${{ needs.version.outputs.semver }}_amd64.deb ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.deb
      - name: Create pacman package
        run: |
          fpm -s dir -t pacman -n controller-monitor -v ${{ needs.version.outputs.semver }} \
            --description "A cross-platform Avalonia UI application for monitoring game controller battery levels" \
            --maintainer "SilentLeader <https://github.com/SilentLeader/>" \
            --url "https://github.com/SilentLeader/controller-battery-monitor" \
            --license "MIT" \
            -C staging .
          mv controller-monitor-${{ needs.version.outputs.semver }}-1-x86_64.pkg.tar.zst ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.pkg.tar.zst
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: ControllerMonitor-Linux-${{ needs.version.outputs.semver }}
          path: src/ControllerMonitor/bin/Release/net9.0/linux-x64/publish/
      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: ControllerMonitor-deb-${{ needs.version.outputs.semver }}
          path: ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.deb
      - name: Upload pacman package
        uses: actions/upload-artifact@v4
        with:
          name: ControllerMonitor-pacman-${{ needs.version.outputs.semver }}
          path: ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.pkg.tar.zst

  release:
    needs: [version, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: ControllerMonitor-Windows-${{ needs.version.outputs.semver }}
          path: artifacts/windows/
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: ControllerMonitor-Linux-${{ needs.version.outputs.semver }}
          path: artifacts/linux/
      - name: Download deb package
        uses: actions/download-artifact@v4
        with:
          name: ControllerMonitor-deb-${{ needs.version.outputs.semver }}
          path: .
      - name: Download pacman package
        uses: actions/download-artifact@v4
        with:
          name: ControllerMonitor-pacman-${{ needs.version.outputs.semver }}
          path: .
      - name: Create archives
        run: |
          cd artifacts/windows
          zip -r ../../ControllerMonitor-Windows-${{ needs.version.outputs.semver }}.zip .
          cd ../linux
          tar -czf ../../ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.tar.gz .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version.outputs.semver }}
          name: Release v${{ needs.version.outputs.semver }}
          body: |
            ## Controller Monitor v${{ needs.version.outputs.semver }}

            This release includes builds for Windows and Linux.

            ### Downloads
            - **Windows**: ControllerMonitor-Windows-${{ needs.version.outputs.semver }}.zip
            - **Linux (tar.gz)**: ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.tar.gz
            - **Linux (deb)**: ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.deb
            - **Linux (pacman)**: ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.pkg.tar.zst

            ### Features
            - Native AOT compilation for improved performance
            - Self-contained executables (no external dependencies required)
            - Single-file Linux executable

            ### Changes
            See commit history for detailed changes in this release.
          make_latest: true
          draft: false
          generate_release_notes: true
          files: |
            ControllerMonitor-Windows-${{ needs.version.outputs.semver }}.zip
            ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.tar.gz
            ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.deb
            ControllerMonitor-Linux-${{ needs.version.outputs.semver }}.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}